### ISSUE TITLE
client.Futures.GetOrdersAsync Issue

### ISSUE THREAD

**Issue by Megwebbiz** [JKorf/Kucoin.Net#64]
Hi
Thanks a lot for your nice project
I have a problem with get open/active orders.
I use client.Futures.GetOrdersAsync to get open orders. Am i right?
when i use client.Futures.GetOrdersAsync with no parameter i see this error:
**"Deserialize JsonSerializationException: Error setting value to 'StopOrderType' on 'Kucoin.Net.Objects.Futures.KucoinFuturesOrder'."**

when i use it like this : var CurOrders = await client.Futures.GetOrdersAsync(symbol:cmbSymbol.Text,status:Kucoin.Net.Objects.KucoinOrderStatus.Active);
i see that current orders count is 0 :
CurOrders.Data.TotalItems=0

thanks for your attention

**Comment by JKorf** [comment]
Hi, I've pushed an update to resolve this

**Comment by Megwebbiz** [comment]
Hi again.
Thank you man.
I installed v3.1.2 but i did not see any change. The problem did not fix.
I have some other problems to.
How can i see my trade history?
I used client.Futures.GetRecentUserTradesAsync() Or client.Futures.GetUserTradesAsync() with no any parameters but i gave error. I attached error file.

Thanks agai
[New Text Document.txt](https://github.com/JKorf/Kucoin.Net/files/7287952/New.Text.Document.txt)
n.

**Comment by JKorf** [comment]
Try again with the latest version, both issues should be resolved

**Comment by Megwebbiz** [comment]
Hi man
I updated to latest version but i have another error :((
**Deserialize JsonSerializationException: Error setting value to 'TimeInForce' on 'Kucoin.Net.Objects.Futures.KucoinFuturesOrder'.**

**Comment by Megwebbiz** [comment]
Hi man
This error has been Solved.
Thank you a lot
